apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: scorecard-project
  labels:
    app: scorecard
spec:
  type: NodePort
  selector:
    app: scorecard-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009