apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: scorecard-project
  labels:
    app: scorecard
spec:
  replicas: 4
  selector:
    matchLabels:
      app: scorecard-nginx
  template:
    metadata:
      labels:
        app: scorecard-nginx
    spec:
      containers:
        - image: nginx:1.21
          name: nginx-container
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "1"
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              port: 80
              path: /bow-type
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              port: 80
              path: /bow-type
            initialDelaySeconds: 15
            periodSeconds: 15
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config