apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: scorecard-project
  labels:
    app: scorecard
data:
  default.conf: |
    upstream scorecard_project {
        server scorecard-service:8000;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://scorecard_project;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
        }
    }