apiVersion: apps/v1
kind: Deployment
metadata:
  name: scorecard-api-app
spec:
  selector:
    matchLabels:
      app: scorecard-api-app
  replicas: 20
  template:
    metadata:
      labels:
        app: scorecard-api-app
    spec:
      containers:
        - name: scorecard-api
          image: scorecard-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
              name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: scorecard-api-service
spec:
  allocateLoadBalancerNodePorts: false
  selector:
    app: scorecard-api-app
  ports:
    - appProtocol: http
      protocol: "TCP"
      port: 8080
      targetPort: http-web-svc
  type: LoadBalancer
