apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: scorecard-project
  labels:
    app: scorecard
data:
  POSTGRES_DB: c2NvcmVjYXJkX2Ri #scorecard_db
  POSTGRES_USER: c2NvcmVjYXJk #scorecard
  POSTGRES_PASSWORD: QXBwMTIzQGxlcw== #App123@les
