apiVersion: batch/v1
kind: Job
metadata:
  name: scorecard-migrations
  namespace: scorecard-project
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: migration-container
          image: whtdrgn101/scorecard-api:latest
          command: ['python', 'init_db.py']
          envFrom:
            - secretRef:
                name: migration-secret
      initContainers:
        - name: init-postgres-service
          image: postgres:10.17
          command: [ 'sh', '-c',
              'until pg_isready -h postgres-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local -p 5432;do echo waiting for database; sleep 2; done;' ]
      restartPolicy: OnFailure
  backoffLimit: 15