apiVersion: v1
kind: Service
metadata:
  name: scorecard-service
  namespace: scorecard-project
  labels:
    app: scorecard
spec:
  selector:
    app: scorecard-app
  ports:
  - port: 8000
    targetPort: 8000
