apiVersion: apps/v1
kind: Deployment
metadata:
  name: scorecard-deployment
  namespace: scorecard-project
  labels:
    app: scorecard
spec:
  replicas: 8
  selector:
    matchLabels: 
      app: scorecard-app
  template:
    metadata:
      labels:
        app: scorecard-app
    spec:
      initContainers:
        - name: init-postgres-service
          image: postgres:10.3
          command: ['sh', '-c', 'until pg_isready -h postgres-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local -p 5432;do echo waiting for database; sleep 2; done;']

      containers:
        - image: whtdrgn101/scorecard-api:latest
          imagePullPolicy: Always
          name: scorecard-container
          envFrom:
            - secretRef:
                name: scorecard-secret
          ports:
            - containerPort: 8000
              name: fastapi
          readinessProbe:
            httpGet:
              port: 8000
              path: /bow-type
            initialDelaySeconds: 15
            periodSeconds: 15
          livenessProbe:
            httpGet: 
              port: 8000
              path: /bow-type
            initialDelaySeconds: 15
            periodSeconds: 15
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "1"